version: 2
jobs:
  build_and_test:
    machine: true
    steps:
      - checkout:
      - run: 
          command: |
            gem install serverspec --no-rdoc --no-ri
            curl -LO https://releases.hashicorp.com/vagrant/2.2.3/vagrant_2.2.3_x86_64.deb
            sudo dpkg -i vagrant_2.2.3_x86_64.deb
            vagrant plugin install vagrant-serverspec
      - run:
          command: ./build.sh
      - run:
          command: TARGET_HOST=default rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
