version: 2
jobs:
  build_and_test:
    machine: true
    steps:
      - run: 
          command: |
            gem install serverspec --no-rdoc --no-ri
            sudo apt-get update -y
            sudo apt-get install vagrant -y
      - run:
          command: ./build.sh
      - run:
          command: TARGET_HOST=default rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
