version: 2
jobs:
  build_and_test:
    machine: true
    steps:
      - run: 
          command: |
            gem install serverspec --no-rdoc --no-ri
            apt-get install vagrant -y
      - run:
          command: make build
      - run:
          command: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
